### ISSUE TITLE
run align_data error

### ISSUE THREAD

**Issue by mapleyuan** [danielroich/PTI#12] opened 2021-07-01 06:18 UTC
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-20f88a29d2a0> in <module>
----> 1 predictor = dlib.shape_predictor(SHAPE_PREDICTOR_PATH)

RuntimeError: Error deserializing object of type int64
   while deserializing a floating point number.
   while deserializing a dlib::matrix
   while deserializing object of type std::vector
   while deserializing object of type std::vector
   while deserializing object of type std::vector

**Comment by danielroich** [comment] 2021-07-01 06:54
This error occurs because align.dat is missing.
Please see #13 
The problem is now fixed

Daniel

**Closed** 2021-07-02 14:01 UTC
